# Day One API development docker-compose file
---
version: '3.8'

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: dayone_todo_provided_server
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: 'Europe/Paris'
    ports:
      - '5432:5432'
    volumes:
      - db_todo_provided_server:/var/lib/postgresql/data/
    restart: always

volumes:
  db_todo_provided_server:
